const { Resend } = require('resend');
require('dotenv').config();

const resendApiKey = process.env.RESEND_API_KEY;
let resend;

if (resendApiKey) {
    resend = new Resend(resendApiKey);
}

const sendDailyManagerReport = async (toEmail, totalSamples, pendingQA, inProduction, dispatched) => {
    if (!resend) {
        console.warn('Resend is not configured. Missing RESEND_API_KEY in .env');
        return false;
    }

    if (!toEmail) {
        console.warn('No email provided for daily report.');
        return false;
    }

    const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>Daily Report</title>
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #F4F7F9; padding: 20px; color: #1A3C58; }
                .container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.05); }
                .header { background-color: #22394B; padding: 30px 20px; text-align: center; }
                .header h1 { color: #ffffff; margin: 0; font-size: 24px; font-weight: 600; letter-spacing: 0.5px; }
                .content { padding: 30px; }
                .content p { font-size: 15px; line-height: 1.6; color: #4a5568; margin-bottom: 25px; }
                .metric-grid { display: table; width: 100%; border-collapse: separate; border-spacing: 15px; margin: -15px; }
                .metric-row { display: table-row; }
                .metric-box { display: table-cell; width: 50%; background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 8px; padding: 20px; text-align: center; }
                .metric-val { font-size: 32px; font-weight: 700; color: #22394B; margin-bottom: 5px; }
                .metric-label { font-size: 12px; font-weight: 600; color: #c27c3e; text-transform: uppercase; letter-spacing: 1px; }
                .footer { background: #f1f5f9; padding: 20px; text-align: center; border-top: 1px solid #e2e8f0; }
                .footer p { font-size: 12px; color: #64748b; margin: 0; }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>Daily Garment Sample Report</h1>
                </div>
                <div class="content">
                    <p>Hello Team,<br><br>Here is the automated end-of-day summary of all garment samples currently tracked on the floor.</p>
                    
                    <div class="metric-grid">
                        <div class="metric-row">
                            <div class="metric-box">
                                <div class="metric-val">${totalSamples}</div>
                                <div class="metric-label">Total Active Samples</div>
                            </div>
                            <div class="metric-box">
                                <div class="metric-val">${inProduction}</div>
                                <div class="metric-label">In Production</div>
                            </div>
                        </div>
                        <div class="metric-row">
                            <div class="metric-box">
                                <div class="metric-val" style="color: #d4a04a;">${pendingQA}</div>
                                <div class="metric-label">QA Pending</div>
                            </div>
                            <div class="metric-box">
                                <div class="metric-val" style="color: #48bb78;">${dispatched}</div>
                                <div class="metric-label">Dispatched</div>
                            </div>
                        </div>
                    </div>

                    <p style="margin-top: 30px;">For a detailed breakdown of current holders and departments, please log in to the Garment Tracker dashboard.</p>
                </div>
                <div class="footer">
                    <p>Generated by Garment Sample Tracking ERP System</p>
                    <p style="margin-top: 5px; opacity: 0.7;">This is an automated message. Please do not reply.</p>
                </div>
            </div>
        </body>
        </html>
    `;

    try {
        const { data, error } = await resend.emails.send({
            from: 'Garment Tracker <onboarding@resend.dev>', // resend.dev is the default sandbox domain
            to: [toEmail],
            subject: '📊 Daily Garment Sample Status Report',
            html: htmlContent,
        });

        if (error) {
            console.error('Error sending Email via Resend:', error);
            return false;
        }

        console.log(`Email sent successfully. ID: ${data.id}`);
        return true;
    } catch (error) {
        console.error('Exception sending Email via Resend:', error);
        return false;
    }
};

module.exports = {
    sendDailyManagerReport
};
