const nodemailer = require('nodemailer');
require('dotenv').config();

// Assuming Google Workspace / Gmail setup
const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS, // This should be an App Password
    },
});

const sendDailyManagerReport = async (toEmail, totalSamples, pendingQA, inProduction, dispatched) => {
    if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
        console.warn('Nodemailer is not configured. Missing SMTP_USER or SMTP_PASS in .env');
        return false;
    }
    if (!toEmail) return false;

    const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>Daily Report</title>
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #F4F7F9; padding: 20px; color: #1A3C58; }
                .container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.05); }
                .header { background-color: #22394B; padding: 30px 20px; text-align: center; }
                .header h1 { color: #ffffff; margin: 0; font-size: 24px; font-weight: 600; letter-spacing: 0.5px; }
                .content { padding: 30px; }
                .content p { font-size: 15px; line-height: 1.6; color: #4a5568; margin-bottom: 25px; }
                .metric-grid { display: table; width: 100%; border-collapse: separate; border-spacing: 15px; margin: -15px; }
                .metric-row { display: table-row; }
                .metric-box { display: table-cell; width: 50%; background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 8px; padding: 20px; text-align: center; }
                .metric-val { font-size: 32px; font-weight: 700; color: #22394B; margin-bottom: 5px; }
                .metric-label { font-size: 12px; font-weight: 600; color: #c27c3e; text-transform: uppercase; letter-spacing: 1px; }
                .footer { background: #f1f5f9; padding: 20px; text-align: center; border-top: 1px solid #e2e8f0; }
                .footer p { font-size: 12px; color: #64748b; margin: 0; }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>Daily Garment Sample Report</h1>
                </div>
                <div class="content">
                    <p>Hello Team,<br><br>Here is the automated end-of-day summary of all garment samples currently tracked on the floor.</p>
                    <div class="metric-grid">
                        <div class="metric-row">
                            <div class="metric-box"><div class="metric-val">${totalSamples}</div><div class="metric-label">Total Active Samples</div></div>
                            <div class="metric-box"><div class="metric-val">${inProduction}</div><div class="metric-label">In Production</div></div>
                        </div>
                        <div class="metric-row">
                            <div class="metric-box"><div class="metric-val" style="color: #d4a04a;">${pendingQA}</div><div class="metric-label">QA Pending</div></div>
                            <div class="metric-box"><div class="metric-val" style="color: #48bb78;">${dispatched}</div><div class="metric-label">Dispatched</div></div>
                        </div>
                    </div>
                </div>
                <div class="footer">
                    <p>Generated by Garment Sample Tracking ERP System</p>
                </div>
            </div>
        </body>
        </html>
    `;

    try {
        await transporter.sendMail({
            from: `"Garment Tracker" <${process.env.SMTP_USER}>`,
            to: toEmail,
            subject: '📊 Daily Garment Sample Status Report',
            html: htmlContent,
        });
        console.log(`Email sent successfully to ${toEmail}`);
        return true;
    } catch (error) {
        console.error('Exception sending Email via Nodemailer:', error);
        return false;
    }
};

const sendExcelReport = async (toEmail, csvData) => {
    if (!process.env.SMTP_USER || !process.env.SMTP_PASS) return false;
    if (!toEmail) return false;

    try {
        await transporter.sendMail({
            from: `"Garment Tracker" <${process.env.SMTP_USER}>`,
            to: toEmail,
            subject: '📊 Garment Samples Export Report',
            html: '<p>Hello,</p><p>Please find the requested Garment Samples export attached as a CSV file.</p>',
            attachments: [
                {
                    filename: 'GTS_Samples_Report.csv',
                    content: Buffer.from(csvData).toString('base64'),
                    encoding: 'base64'
                }
            ]
        });
        console.log(`Excel Email sent successfully to ${toEmail}`);
        return true;
    } catch (error) {
        console.error('Exception sending Excel Email via Nodemailer:', error);
        return false;
    }
};

module.exports = {
    sendDailyManagerReport,
    sendExcelReport
};
